pipeline {
  agent any
  environment {
    DOCKERHUB = credentials('dockerhub-creds-id')
    IMAGE = 'priyanshuprafful/infra-deployer'
    CONTAINER_NAME = 'infra-deployer'
    APP_PORT = '5000'
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/priyanshuprafful/infra-deployer.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t ${IMAGE}:latest .'
      }
    }

    stage('Docker Login & Push') {
      steps {
        sh 'echo $DOCKERHUB_PSW | docker login -u $DOCKERHUB_USR --password-stdin'
        sh 'docker push ${IMAGE}:latest'
      }
    }

    stage('Deploy Container') {
      steps {
        sh 'docker rm -f ${CONTAINER_NAME} || true'
        sh 'docker run -d --name ${CONTAINER_NAME} -p ${APP_PORT}:${APP_PORT} ${IMAGE}:latest'
      }
    }
  }
}
